apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: services-district12-tls
  namespace: default
spec:
  secretName: services-district12-tls
  dnsNames:
  - services.district12.xyz
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer