apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
data:
  prometheus.yml: |-
    global:
      scrape_interval: 15s
      evaluation_interval: 15s

    scrape_configs:
      - job_name: "tick12-auth-service"
        metrics_path: "/metrics"
        static_configs:
          - targets:
              - "tick12-auth-service:8000"  # Use the correct endpoint for metrics

      - job_name: "tick12-ticket-service"
        metrics_path: "/metrics"
        static_configs:
          - targets:
              - "tick12-ticket-service:8001"  # Use the correct endpoint for metrics

      - job_name: "tick12-price-service"
        metrics_path: "/metrics"
        static_configs:
          - targets:
              - "tick12-price-service:8002"  # Use the correct endpoint for metrics

      - job_name: "tick12-train-service"
        metrics_path: "/metrics"
        static_configs:
          - targets:
              - "tick12-train-service:8003"  # Use the correct endpoint for metrics

      - job_name: "tick12-cache-service"
        metrics_path: "/metrics"
        static_configs:
          - targets:
              - "tick12-cache-service:8005"  # Use the correct endpoint for metrics
